### ISSUE TITLE
API Issues

### ISSUE THREAD

**Issue by Lykoto-M** [axsddlr/lost_ark_api#4]
Whenever I use the forums api link "http://lostarkapi.herokuapp.com/v1/forums" on my Discord bot to send out each new forum post I get this error: 'Expecting value', 'Internal Server Error').

**Comment by axsddlr** [comment]
ill check it out tomorrow, thanks for the info. they likely changed the api

**Comment by axsddlr** [comment]
> Whenever I use the forums api link "http://lostarkapi.herokuapp.com/v1/forums" on my Discord bot to send out each new forum post I get this error: 'Expecting value', 'Internal Server Error').

fixed here: https://github.com/axsddlr/lost_ark_api/commit/bd5b22a78b8f020c8a49af709ba82bdf12b01b79

**Comment by Lykoto-M** [comment]
Still getting the issue when using "http://lostarkapi.herokuapp.com/v1/forums"

**Comment by axsddlr** [comment]
No issues at all on my end. Went to that endpoint and received proper json
values.  Try again.

**Comment by Lykoto-M** [comment]
requests.exceptions.JSONDecodeError: [Errno Expecting value] Internal Server Error: 0

is what I get

**Comment by axsddlr** [comment]
Have any excerpt of the code you’re running?

**Comment by Lykoto-M** [comment]
```py
#Gets Lost Ark Forum Post
def lost_ark_forum():
    URL ='http://lostarkapi.herokuapp.com/v2/forums/Downtime'
    r = requests.get(url=URL)
    data = r.json()
    return data["data"][0]

async def forum_task():
    forum_old = lost_ark_forum()["created_at"]
    while True:
        forum_new = lost_ark_forum()
        forumembed = hikari.Embed(title=forum_new()["title"], description=forum_new()["post_body"], url=forum_new()["url"], color="#DAA520")
        forumembed.set_author(name=forum_new()["author"], icon="https://pbs.twimg.com/profile_images/1492289372477030401/wj9cuyth_400x400.jpg")
        forumembed.set_footer(text=forum_new()["created_at"])
        print("test")
        if forum_old != forum_new["created_at"]:
            forum_old = forum_new["created_at"]
            await bot.rest.create_message(953264509785628682, forumembed)
        await asyncio.sleep(600)

@bot.listen(hikari.StartedEvent)
async def on_started(_):
    global running_task
    running_task = asyncio.create_task(forum_task())

@bot.listen(hikari.StoppingEvent)
async def on_stopping(_):
    global running_task
    if running_task is not None:
        running_task.cancel()
```

**Comment by axsddlr** [comment]
interesting i see nothing wrong with the json mapping in this code. only thing i would try to wrap json value calls in a try/except

**Comment by Lykoto-M** [comment]
I'll give it a shot.

**Comment by axsddlr** [comment]
> I'll give it a shot.

created a basic discord bot for lost ark: https://github.com/axsddlr/lost_ark_bot

set up a bot account and try it

another issue with my api would be because herokuapp free version likely about to reach data cap

**Comment by axsddlr** [comment]
Also, test the endpoint in incognito or clean cache. Works in my lost ark
discord bot with no issues
